name: pure
description: A Social Network Messenger.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  adaptive_dialog: ^1.1.0
  
  app_settings: ^4.1.1
  badges: ^2.0.1
  cupertino_icons: ^1.0.3
  device_info_plus: ^3.2.2
  dio: ^4.0.0
  email_validator: ^2.0.1
  file_picker: ^4.2.3
  flash: ^2.0.1
  flex_color_scheme: ^4.1.1
  float_column: ^1.2.1
  flutter_easyloading: ^3.0.0
  flutter_link_previewer: ^2.6.1
  flutter_linkify: ^5.0.2
  font_awesome_flutter: ^9.2.0
  go_router: ^3.0.3
  intl: ^0.17.0
  linkify: ^4.1.0
  palette_generator: ^0.3.2
  permission_handler: ^9.2.0
  photo_view: ^0.13.0
  share_plus: ^3.1.0
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  random_color: ^1.0.6-nullsafety
  smooth_page_indicator: ^1.0.0+2
  stream_transform: ^2.0.0
  timeago: ^3.1.0
  url_launcher: ^6.0.17
  uuid: ^3.0.4
  glassmorphism: ^3.0.0
  google_fonts: ^2.3.0
  nanoid: ^1.0.0
  numberpicker: ^2.1.1
  http: ^0.13.4 
  checkmark: ^0.0.2+1
  auto_animated: ^3.0.1
  flutter_native_splash: ^2.0.5


  # Authentication
  sign_in_with_apple: ^3.3.0
  google_sign_in: ^5.2.1

  # Screen Utilities
  flutter_screenutil: ^5.0.0+2

  # Images
  image_picker: ^0.8.4
  cached_network_image: ^3.1.0
  image_cropper: ^1.4.1
  flutter_image_compress: ^1.1.0

  # State Management
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3

  # Firebase
  cloud_firestore: ^3.1.0
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  firebase_database: ^9.0.7
  firebase_dynamic_links: ^4.0.7
  firebase_messaging: ^11.1.0
  firebase_storage: ^10.1.0
  firebase_crashlytics: ^2.4.4

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true


  assets:
    - assets/images/
    - assets/images/congratulations_gif/

  fonts:
    - family: Migra
      fonts:
        - asset: assets/fonts/Migra-Bold.otf
          weight: 800

    - family: PublicSans
      fonts:
        - asset: assets/fonts/PublicSans-Light.otf
          weight: 300
        - asset: assets/fonts/PublicSans-Regular.otf
          weight: 400
        - asset: assets/fonts/PublicSans-Medium.otf
          weight: 500
        - asset: assets/fonts/PublicSans-SemiBold.otf
          weight: 600
        - asset: assets/fonts/PublicSans-Bold.otf
          weight: 700




flutter_native_splash:

  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  #color: "#42a5f5"
  background_image: "assets/images/background.png"

  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: "assets/images/logo.png"

  # This property allows you to specify an image used as branding in the splash screen. It must be
  # a png file. Currently, it is only supported for Android and iOS.
  #branding: assets/dart.png

  # Specify your branding image for dark mode.
  #branding_dark: assets/dart_dark.png

  # To position the branding image at the bottom of the screen you can use bottom, bottomRight,
  # and bottomLeft. The default values is bottom if not specified or specified something else.
  #
  # Make sure this content mode value should not be similar to android_gravity value and
  # ios_content_mode value.
  #branding_mode: bottom

  # The color_dark, background_image_dark, and image_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png

  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  #android: false
  #ios: false
  #web: false

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  # To hide the notification bar, use the fullscreen parameter.  Has no effect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  #fullscreen: true
  
  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s) 
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'